import { Injectable } from '@angular/core';
import { PdfService } from 'src/app/spms/service/pdf.service';
import { SignatoriesService } from './signatories.service';
import { HttpClient } from '@angular/common/http';
import { SpmsApiService } from './spms-api.service';
import { api } from 'src/app/connection';

@Injectable({
  providedIn: 'root',
})
export class ReportMporService {
  constructor(
    private reportService: PdfService,
    private signatoriesService: SignatoriesService,
    private http: HttpClient,
    private url: SpmsApiService
  ) {}

  post_print_mpor(data: any) {
    return this.http.post<any[]>(api + this.url.post_print_mpor(), data, {
      responseType: `json`,
    });
  }

  ReportMPOR(strategic: any, core: any, support: any) {
    let content: any = [];
    let tableBody: any = [];
    let title1 = 'PROVINCIAL BLA BLA BLA OFFICE';
    let title2 = 'MONTHLY PERFORMANCE OUTPUT REPORT';

    tableBody.push(
      [
        {
          text: 'MAJOR FINAL OUTPUT',
          margin: [0, 13, 0, 0],
          rowSpan: 3,
          fontSize: 12,
          alignment: 'center',
          bold: true,
        },
        {
          text: 'ACCOMPLISHMENTS',
          colSpan: 23,
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      [
        {},
        {
          text: 'QUALITY',
          fontSize: 8,
          colSpan: 5,
          alignment: 'center',
          bold: true,
        },
        {},
        {},
        {},
        {},
        {
          text: 'QUANTITY',
          fontSize: 8,
          colSpan: 9,
          alignment: 'center',
          bold: true,
        },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {
          text: 'TIMELINESS',
          fontSize: 8,
          colSpan: 9,
          alignment: 'center',
          bold: true,
        },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      [
        {},
        {
          text: 'Wk1',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: 'Wk2',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: 'Wk3',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: 'Wk4',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: 'TOTAL',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: 'Wk1',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: '',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: 'Wk2',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: '',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: 'Wk3',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: '',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: 'Wk4',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: '',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: 'TOTAL',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: 'Wk1',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: '',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: 'Wk2',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: '',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: 'Wk3',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: '',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: 'Wk4',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: '',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
        {
          text: 'TOTAL',
          fontSize: 8,
          alignment: 'center',
          bold: true,
        },
      ]
    );

    tableBody.push([
      {
        text: '1.' + ' ' + 'STRATEGIC FUNCTIONS',
        fontSize: 11,
        alignment: 'left',
        bold: true,
      },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ]);
    strategic.map((a: any, index: number) => {
      tableBody.push([
        { text: '1.' + (index + 1) + ' ' + a.mfo, margin: [15, 0, 0, 0] },
        { text: a.qtyWk1, fontSize: 8 },
        { text: a.qtyWk2, fontSize: 8 },
        { text: a.qtyWk3, fontSize: 8 },
        { text: a.qtyWk4, fontSize: 8 },
        { text: a.total, fontSize: 8 },
        { text: 6, fontSize: 8 },
        { text: 7, fontSize: 8 },
        { text: 8, fontSize: 8 },
        { text: 9, fontSize: 8 },
        { text: 10, fontSize: 8 },
        { text: 11, fontSize: 8 },
        { text: 12, fontSize: 8 },
        { text: 13, fontSize: 8 },
        { text: 14, fontSize: 8 },
        { text: 15, fontSize: 8 },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ]);
    });

    tableBody.push([
      {
        text: '2.' + ' ' + 'CORE FUNCTIONS',
        fontSize: 11,
        alignment: 'left',
        bold: true,
      },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ]);
    core.map((a: any, index: number) => {
      tableBody.push([
        { text: '2.' + (index + 1) + ' ' + a.mfo, margin: [15, 0, 0, 0] },
        { text: a.qtyWk1, fontSize: 8 },
        { text: a.qtyWk2, fontSize: 8 },
        { text: a.qtyWk3, fontSize: 8 },
        { text: a.qtyWk4, fontSize: 8 },
        { text: a.total, fontSize: 8 },
        { text: 6, fontSize: 8 },
        { text: 7, fontSize: 8 },
        { text: 8, fontSize: 8 },
        { text: 9, fontSize: 8 },
        { text: 10, fontSize: 8 },
        { text: 11, fontSize: 8 },
        { text: 12, fontSize: 8 },
        { text: 13, fontSize: 8 },
        { text: 14, fontSize: 8 },
        { text: 15, fontSize: 8 },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ]);
    });

    tableBody.push([
      {
        text: '3.' + ' ' + 'SUPPORT FUNCTIONS',
        fontSize: 11,
        alignment: 'left',
        bold: true,
      },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ]);
    support.map((a: any, index: number) => {
      tableBody.push([
        { text: '3.' + (index + 1) + ' ' + a.mfo, margin: [15, 0, 0, 0] },
        { text: a.qtyWk1, fontSize: 8 },
        { text: a.qtyWk2, fontSize: 8 },
        { text: a.qtyWk3, fontSize: 8 },
        { text: a.qtyWk4, fontSize: 8 },
        { text: a.total, fontSize: 8 },
        { text: 6, fontSize: 8 },
        { text: 7, fontSize: 8 },
        { text: 8, fontSize: 8 },
        { text: 9, fontSize: 8 },
        { text: 10, fontSize: 8 },
        { text: 11, fontSize: 8 },
        { text: 12, fontSize: 8 },
        { text: 13, fontSize: 8 },
        { text: 14, fontSize: 8 },
        { text: 15, fontSize: 8 },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ]);
    });

    content.push([
      {
        margin: [0, 20, 0, 0],
        alignment: 'justify',
        columns: [
          {
            text: 'EMPLOYEE NAME: LOWELL DAVE A. LARGO',
            fontSize: 10,
            width: 790,
            bold: true,
          },
          {
            text: 'MONTH: JANUARY 2024',
            fontSize: 10,
            alignment: 'left',
            bold: true,
          },
        ],
      },
      {
        style: 'tableExample',
        margin: [67, 20, 5, 0],
        table: {
          widths: [
            170,
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
            '*',
          ],
          body: tableBody,
        },
      },
    ]);

    this.reportService.reportTarget(content, {
      isPortrait: false,
      title1: title1,
      title2: title2,
    });
  }
}
